# Generated by Django 4.1.3 on 2023-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_address_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
